/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;

import Dtos.CategoriaDTO;
import Dtos.ProductoDTO;
import Dtos.UsuarioDTO;
import Modelos.ComboItem;
import Modelos.ModeloCategorias;
import Modelos.ModeloProducto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ppluigui
 */
public class DetalleProducto extends javax.swing.JInternalFrame {

    private String estadoDetalleProducto = "AGREGAR";
    private int productoId = 0;
    
    /**
     * Creates new form DetalleProducto
     */
    public DetalleProducto() {
        initComponents();
        llenarCategorias();
        btnModificar.setVisible(false);
    }
    
    
    public void establecerProducto( int productoId ){
        
        this.estadoDetalleProducto = "MODIFICAR";
        btnAgregar.setVisible(false);
        btnModificar.setVisible(true);
        btnLimpiar.setVisible(false);
        
        cargarDetallesProducto(productoId);
        this.productoId = productoId;
        
    }
    
    private void cargarDetallesProducto(int productoId) {
        
        ModeloProducto mProducto = new ModeloProducto();
        ProductoDTO producto = mProducto.buscarProductoPorId(productoId);
        
        txtClave.setText( producto.getClave() );
        txtNombre.setText( producto.getNombre() );
        txtPrecio.setText( String.valueOf(producto.getPrecio())  );
        txtdetalles.setText( producto.getDetalles() );
        
        
        ModeloCategorias mCategoria = new ModeloCategorias();
        CategoriaDTO categoriaDTO = mCategoria.buscarPorId(producto.getCategoria_id());
        

        seleccionarCategoria(categoriaDTO.getNombre());
        
    }
    
    
    private void seleccionarCategoria(String categoriaNombre) {
        
        ComboItem item;
        for (int i = 0; i < ddCategoria.getItemCount(); i++)
        {
            item = (ComboItem)ddCategoria.getItemAt(i);
            if (item.getKey().equalsIgnoreCase(categoriaNombre))
            {
                ddCategoria.setSelectedIndex(i);
                break;
            }
        }
        
      
    }
    

    public void llenarCategorias(){
        
        ArrayList<CategoriaDTO> listCategorias = null;
        ModeloCategorias mCategorias = new ModeloCategorias();
        
        
        listCategorias = mCategorias.obtenerLista();
        
        ddCategoria.addItem( new ComboItem( "Seleccione una...", 0));
        
        for (CategoriaDTO categoria : listCategorias) {    
            
            String PrvNombre = categoria.getNombre();
            int PrvId = categoria.getId_categoria();
            
            
            ddCategoria.addItem(  new ComboItem(PrvNombre, PrvId));
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtdetalles = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        ddCategoria = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Detalle Producto");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto-categoria.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/precio.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombre-de-producto.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caracteristica.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-producto.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoria.png"))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(223, 120, 97));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar-white.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        btnAgregar.setBackground(new java.awt.Color(223, 120, 97));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(223, 120, 97));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar-white.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(223, 120, 97));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-white.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        btnLimpiar.setBackground(new java.awt.Color(223, 120, 97));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpiar-white.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClave)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtdetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(ddCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClave)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ddCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        
        ProductoDTO producto = new ProductoDTO();
        
        int categoriaId = ddCategoria.getItemAt( ddCategoria.getSelectedIndex()).getValue();
        
        producto.setClave( txtClave.getText() );
        producto.setNombre( txtNombre.getText());
        producto.setDetalles( txtdetalles.getText());
        producto.setPrecio( Double.valueOf( txtPrecio.getText() )  );
        producto.setCategoria_id( categoriaId );
        producto.setProveedor_id( UsuarioDTO.getId() );
        
        
        ModeloProducto mProducto = new ModeloProducto();
        mProducto.guardarProducto(producto);
        
        JOptionPane.showMessageDialog(null, "Producto Almacenado Satisfactoriamente");
        dispose();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        ProductoDTO producto = new ProductoDTO();
        
        int categoriaId = ddCategoria.getItemAt( ddCategoria.getSelectedIndex()).getValue();
        
        producto.setId_producto( this.productoId );
        producto.setClave( txtClave.getText() );
        producto.setNombre( txtNombre.getText());
        producto.setDetalles( txtdetalles.getText());
        producto.setPrecio( Double.valueOf( txtPrecio.getText() )  );
        producto.setCategoria_id( categoriaId );
        producto.setProveedor_id( UsuarioDTO.getId() );
        
        
        ModeloProducto mProducto = new ModeloProducto();
        mProducto.modificarProducto(producto);
        
        JOptionPane.showMessageDialog(null, "Producto Modificado Satisfactoriamente");
        dispose();
        


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtClave.setText( "" );
        txtNombre.setText( "" );
        txtPrecio.setText( ""  );
        txtdetalles.setText( "" );
          ddCategoria.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<ComboItem> ddCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtdetalles;
    // End of variables declaration//GEN-END:variables
}
