/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;

import Dtos.UsuarioDTO;


/**
 *
 * @author ppluigui
 */
public class Escritorio extends javax.swing.JFrame {
    private static UsuarioDTO usuarioEnSesion; 
    
    
    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        configurarBotones();
        
        
        lblUsuario.setText( usuarioEnSesion.getNombre()  );
    }
    
    
    private void configurarBotones(){
        if("PROVEEDOR".equals(UsuarioDTO.getTipo_usuario())  ) {
            
            btnComprar.setVisible(false);
            btnMisPedidos.setVisible(false);
            btnEnviarComentarios.setVisible(false);
            
            btnAgregarProductos.setText("<html>Agregar<br />Producto</html>");

        }else{
            btnAgregarProductos.setVisible(false);
            btnPedidos.setVisible(false);
            btnComentariosCtes.setVisible(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnMisPedidos = new javax.swing.JButton();
        btnEnviarComentarios = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAgregarProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnComentariosCtes = new javax.swing.JButton();
        panelEscritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(236, 179, 144));
        jPanel1.setForeground(new java.awt.Color(236, 179, 144));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario-white.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial Hebrew", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("jLabel2");

        btnInicio.setBackground(new java.awt.Color(235, 207, 190));
        btnInicio.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house-white.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnComprar.setBackground(new java.awt.Color(235, 207, 190));
        btnComprar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comprar-white.png"))); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnMisPedidos.setBackground(new java.awt.Color(235, 207, 190));
        btnMisPedidos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnMisPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedido-white.png"))); // NOI18N
        btnMisPedidos.setText("Mi Pedido");
        btnMisPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMisPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisPedidosActionPerformed(evt);
            }
        });

        btnEnviarComentarios.setBackground(new java.awt.Color(235, 207, 190));
        btnEnviarComentarios.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnEnviarComentarios.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comentario-white.png"))); // NOI18N
        btnEnviarComentarios.setText("Comentario");
        btnEnviarComentarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEnviarComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComentariosActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(235, 207, 190));
        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAgregarProductos.setBackground(new java.awt.Color(235, 207, 190));
        btnAgregarProductos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAgregarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAgregarProductos.setText("Agregar");
        btnAgregarProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductosActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(235, 207, 190));
        btnPedidos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedido-white.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnComentariosCtes.setBackground(new java.awt.Color(235, 207, 190));
        btnComentariosCtes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnComentariosCtes.setForeground(new java.awt.Color(255, 255, 255));
        btnComentariosCtes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comentario-white.png"))); // NOI18N
        btnComentariosCtes.setText("Comentarios");
        btnComentariosCtes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComentariosCtes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosCtesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMisPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComentariosCtes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMisPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarComentarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComentariosCtes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(900, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        HacerPedido frmPedido = new HacerPedido();
        panelEscritorio.add(frmPedido);
//        frmPedido.setLocation(  this.getWidth()/2 - frmPedido.getWidth()/2   ,  this.getHeight()/2 - frmPedido.getHeight()/2);
        frmPedido.setVisible(true);
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

       dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnMisPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisPedidosActionPerformed

        MisPedidos frmPedidos = new MisPedidos();
        panelEscritorio.add(frmPedidos);
        frmPedidos.setVisible(true);
        
        
    }//GEN-LAST:event_btnMisPedidosActionPerformed

    private void btnEnviarComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComentariosActionPerformed
        EnviarComentario frmComentarios = new EnviarComentario();
        panelEscritorio.add(frmComentarios);
        frmComentarios.setVisible(true);
    }//GEN-LAST:event_btnEnviarComentariosActionPerformed

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductosActionPerformed
        ListaProductos frmListaProductos = new ListaProductos();
        panelEscritorio.add(frmListaProductos);
        frmListaProductos.setVisible(true);
        
        
    }//GEN-LAST:event_btnAgregarProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed

        ListadoPedidos frmListadoPedidos = new ListadoPedidos();
        panelEscritorio.add(frmListadoPedidos);
        frmListadoPedidos.setVisible(true);
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnComentariosCtesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosCtesActionPerformed
        ListaComentarios frmListaComentarios = new ListaComentarios();
        panelEscritorio.add(frmListaComentarios);
        frmListaComentarios.setVisible(true);
    }//GEN-LAST:event_btnComentariosCtesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductos;
    private javax.swing.JButton btnComentariosCtes;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEnviarComentarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMisPedidos;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JDesktopPane panelEscritorio;
    // End of variables declaration//GEN-END:variables
}
