/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;


import Dtos.PedidoDetalleDTO;
import Dtos.PedidoEncabezadoDTO;
import Dtos.ProductoDTO;
import Dtos.ProveedorDTO;
import Dtos.UsuarioDTO;
import Modelos.ModeloProveedor;
import java.util.ArrayList;
import Modelos.ComboItem;
import Modelos.ModeloPedido;
import Modelos.ModeloProducto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ppluigui
 */
public class HacerPedido extends javax.swing.JInternalFrame {
    
    private static UsuarioDTO usuarioEnSesion; 
    
    
    /**
     * Creates new form HacerPedido
     */
    public HacerPedido() {
        initComponents();
        llenarComboProveedores();
        LimpiarTablaPedidos();
    }
    
    private void llenarComboProveedores(){
        
        ArrayList<ProveedorDTO> listProveedores = null;
        ModeloProveedor mdlPrv = new ModeloProveedor();
        listProveedores = mdlPrv.obtenerLista();
        
        ddProveedor.addItem( new ComboItem( "Seleccione uno...", 0));
        
        for (ProveedorDTO proveedor : listProveedores) {    
            
            String PrvNombre = proveedor.getNombre();
            int PrvId = proveedor.getId();
            
            // Ponemos la primer letra en mayuscula y las demas en minuisculas
            PrvNombre = PrvNombre.substring(0, 1).toUpperCase() + PrvNombre.substring(1).toLowerCase();
            
            
            ddProveedor.addItem(  new ComboItem(PrvNombre, PrvId));
        }
        
    }
    
    
    private void LimpiarTablaPedidos(){
        
        DefaultTableModel dtm = (DefaultTableModel) tablaDetalle.getModel();
        dtm.setRowCount(0);
    }
    
    
    private void agregarProductoAPedido(ProductoDTO producto, int cantidad){
        
        DefaultTableModel dtm = (DefaultTableModel) tablaDetalle.getModel();
        
        Object[] fila = new Object[5];
        
        fila[0] = producto.getClave();
        fila[1] = producto.getNombre();
        fila[2] = cantidad;
        fila[3] = producto.getPrecio();
        fila[4] = cantidad*producto.getPrecio();
                
        dtm.addRow(fila);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ddProveedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Hacer Pedido");
        setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Haga_su_pedido.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(235, 207, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hacer_pedido_a.png"))); // NOI18N

        ddProveedor.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ddProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddProveedor)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDetalle);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cantidad.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N

        txtId.setBackground(new java.awt.Color(235, 207, 190));
        txtId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        txtCantidad.setBackground(new java.awt.Color(235, 207, 190));
        txtCantidad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setText("1");

        jButton1.setBackground(new java.awt.Color(223, 120, 97));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito-white.png"))); // NOI18N
        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(223, 120, 97));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpiar-white.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        
            String claveProducto = txtId.getText();
            
            ModeloProducto mProducto = new ModeloProducto();
            ProductoDTO producto =  mProducto.buscarProductoPorClave(claveProducto);
            int cantidad = Integer.valueOf(txtCantidad.getText());
            agregarProductoAPedido(producto, cantidad);
            
            
            
            if(producto.getId_producto() == 0){
                 JOptionPane.showMessageDialog(null, "Producto No Encontrado");
            } else {
                
                
            }
            
        }
        
    }//GEN-LAST:event_txtIdKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            LimpiarTablaPedidos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ddProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        int proveedorId = ddProveedor.getItemAt( ddProveedor.getSelectedIndex()).getValue();
        
        // Validamos que tenga seleccionado un Proveedor
        if(proveedorId == 0){
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un Proveedor");
            return;
        }
        
        
        // Preparamos los objetos para guardar el pedido
        PedidoEncabezadoDTO pedEncabezado = crearEncabezado();
        
        ArrayList<PedidoDetalleDTO> pedDetalles = crearDetalles();
        
        ModeloPedido mPedido = new ModeloPedido();
        mPedido.guardarPedido(pedEncabezado, pedDetalles);
        
        JOptionPane.showMessageDialog(null, "Pedido Guardado Correctamente");
        LimpiarTablaPedidos();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private PedidoEncabezadoDTO crearEncabezado() {
        
        PedidoEncabezadoDTO pedEncabezado = new PedidoEncabezadoDTO();
        
        int proveedorId = ddProveedor.getItemAt( ddProveedor.getSelectedIndex()).getValue();
        Double totalDeProductos = calcularTotalProductos();
        Date fechaHoySinFormato = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
        String fechaHoy= formatter.format(fechaHoySinFormato);  
        
        pedEncabezado.setProveedor_id(proveedorId);
        pedEncabezado.setCliente_id( usuarioEnSesion.getId() );
        pedEncabezado.setFecha(fechaHoy.toString());
        pedEncabezado.setTotal(totalDeProductos);
        pedEncabezado.setStatus(1);
        return pedEncabezado;
    }
    
    private ArrayList<PedidoDetalleDTO> crearDetalles(){
        
        ArrayList<PedidoDetalleDTO> pedDetalles = new ArrayList<PedidoDetalleDTO>();
        PedidoDetalleDTO pedDetalle;
        ModeloProducto mProducto = new ModeloProducto();
        
        // Obtenemos todos los datos dentro de la tabla 
        DefaultTableModel dtm = (DefaultTableModel) tablaDetalle.getModel();
        
        int totalItems = tablaDetalle.getRowCount();
        
        for(int i = 0; i<=totalItems-1 ; i++) {
            pedDetalle = new PedidoDetalleDTO();
            
            
            String codigo   = tablaDetalle.getValueAt(i, 0).toString();
            ProductoDTO prodDto = mProducto.buscarProductoPorClave(codigo);
            
            int productoId = prodDto.getId_producto();
            int cantidad = Integer.valueOf(tablaDetalle.getValueAt(i, 2).toString());
            Double precio   = Double.valueOf(tablaDetalle.getValueAt(i, 3).toString());
            Double total    = cantidad*precio;
            
            pedDetalle.setId_producto(productoId);
            pedDetalle.setCantidad(cantidad);
            pedDetalle.setPrecio(precio);
            
            
            
            
            pedDetalles.add(pedDetalle);
            pedDetalle = null;
        }
        
        return pedDetalles;
    }
    
    
    
    
    private Double calcularTotalProductos(){
        Double total = 0.0;
        
        // Obtenemos todos los datos dentro de la tabla 
        DefaultTableModel dtm = (DefaultTableModel) tablaDetalle.getModel();
        
        for(int i = 0; i<=tablaDetalle.getRowCount()-1 ; i++) {
            int cantidad = Integer.valueOf(tablaDetalle.getValueAt(i, 2).toString());
            Double precio   = Double.valueOf(tablaDetalle.getValueAt(i, 3).toString());
                   total    += cantidad*precio;
           
        }
        
        return total;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> ddProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
