/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;

import Dtos.ProductoDTO;
import Modelos.ModeloProducto;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ppluigui
 */
public class ListaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaProductos
     */
    public ListaProductos() {
        initComponents();
        listarProductos();
    }

    
    private void listarProductos(){
        
        ModeloProducto mProducto = new ModeloProducto();
        ArrayList<ProductoDTO> listaProductos = mProducto.listarTodos();
        
        DefaultTableModel dtm = (DefaultTableModel) tblProductos.getModel();
        dtm.setRowCount(0);
        
        for( ProductoDTO producto : listaProductos ) {
           
            Object[] fila = new Object[5];
        
            fila[0] = producto.getId_producto();
            fila[1] = producto.getClave();
            fila[2] = producto.getNombre();
            fila[3] = producto.getPrecio();
            fila[4] = producto.getUnidad();

            dtm.addRow(fila);
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Productos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto-categoria.png"))); // NOI18N

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Clave", "Nombre", "Precio", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnAgregar.setBackground(new java.awt.Color(223, 120, 97));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(223, 120, 97));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar-white.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        DetalleProducto frmDetalleProducto = new DetalleProducto();
        
        if(!frmDetalleProducto.isVisible()){
            
            JDesktopPane escritorio = (JDesktopPane) getParent();
            escritorio.add(frmDetalleProducto);
            frmDetalleProducto.toFront();
            frmDetalleProducto.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        
        int selectedIndex = tblProductos.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) tblProductos.getModel();
        DetalleProducto frmDetalleProducto = new DetalleProducto();
        
        // Con este IF detectamos si hizo doble click en algun producto
        if (evt.getClickCount() == 2 && selectedIndex != -1) {
            
            // Obtenemmos que producto quiere editar el Proveedor
            
            int productoId = Integer.valueOf( dtm.getValueAt(selectedIndex, 0).toString() );
            
            JDesktopPane escritorio = (JDesktopPane) getParent();
            escritorio.add(frmDetalleProducto);
            frmDetalleProducto.establecerProducto(productoId);
            frmDetalleProducto.toFront();
            frmDetalleProducto.setVisible(true);
            
        }
        
        
        
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) tblProductos.getModel();
        
        
        if(dtm.getRowCount() > 0) {
            if( !tblProductos.getSelectionModel().isSelectionEmpty()) {
                 
                 int selectedIndex = tblProductos.getSelectedRow();
                 int productoId = Integer.valueOf( dtm.getValueAt(selectedIndex, 0).toString() );
                 
                int opcion = JOptionPane.showConfirmDialog(null, "Esta seguro de que quiere eliminar este producto?");
                // 0=yes, 1=no, 2=cancel
                if(opcion == 0){
                    ModeloProducto mProducto = new ModeloProducto();
                    mProducto.eliminarProducto(productoId);
                    
                    
                    JOptionPane.showMessageDialog(null, "Producto Eliminado");
                    dispose();

                }else{
                    JOptionPane.showMessageDialog(null, "Producto No Modificado");
                }  
                 
                 
                 
                 
                 
                 
                 
                 
                 
            }else{
                
                // Llegamos aqui cuando hay pedidos en la lista pero no hay seleccion
                 JOptionPane.showMessageDialog(null, "Seleccione un Producto Primero");
            }
        }else{
            // Llegamos aqui cuando no hay pedidos en la lista
            JOptionPane.showMessageDialog(null, "Seleccione un Producto Primero");
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
