/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;

import Dtos.PedidoDTO;
import Dtos.ProveedorDTO;
import Dtos.UsuarioDTO;
import Modelos.ComboItem;
import Modelos.ModeloPedido;
import Modelos.ModeloProveedor;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ppluigui
 */
public class ListadoPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MisPedidos
     */
    public ListadoPedidos() {
        initComponents();
        listarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddColonia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pedidos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedidos.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colonia.png"))); // NOI18N

        ddColonia.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ddColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddColoniaActionPerformed(evt);
            }
        });

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Num. Pedido", "Fecha", "Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPedidos);

        jButton1.setBackground(new java.awt.Color(223, 120, 97));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf-white.png"))); // NOI18N
        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ddColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ddColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listarPedidos() {
        
        int proveedorId = UsuarioDTO.getId();
        
        DefaultTableModel dtm = (DefaultTableModel) tablaPedidos.getModel();
        dtm.setRowCount(0);
        ModeloPedido mPedido = new ModeloPedido();
        ArrayList<PedidoDTO> pedidos = mPedido.listaPorProveedor(proveedorId);
        
        
        
        for( PedidoDTO pedido : pedidos ) {
           
            Object[] fila = new Object[4];
        
            fila[0] = pedido.getId_pedido();
            fila[1] = pedido.getFecha();
            fila[2] = pedido.getTotal();
            fila[3] = pedido.getStatus();

            dtm.addRow(fila);
        }
        
    }
    
    
    
    
    private void ddColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddColoniaActionPerformed
         
        int proveedorId = ddColonia.getItemAt( ddColonia.getSelectedIndex()).getValue();
        DefaultTableModel dtm = (DefaultTableModel) tablaPedidos.getModel();
        dtm.setRowCount(0);
        
        
        
    }//GEN-LAST:event_ddColoniaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        generarPdf();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void generarPdf(){
         DefaultTableModel dtm = (DefaultTableModel) tablaPedidos.getModel();
        
        
        if(dtm.getRowCount() > 0) {
            if( !tablaPedidos.getSelectionModel().isSelectionEmpty()) {
                 
                 int selectedIndex = tablaPedidos.getSelectedRow();
                 int pedidoId = Integer.valueOf( dtm.getValueAt(selectedIndex, 0).toString() );
                 
                 
                 
                 JOptionPane.showMessageDialog(null, "Generar PDF del pedido: " + pedidoId);
                 
                 
                 
            }else{
                
                // Llegamos aqui cuando hay pedidos en la lista pero no hay seleccion
                 JOptionPane.showMessageDialog(null, "Seleccione un Pedido Primero");
            }
        }else{
            // Llegamos aqui cuando no hay pedidos en la lista
            JOptionPane.showMessageDialog(null, "Seleccione un Pedido Primero");
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> ddColonia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
