/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastore;

import Dtos.ClienteDTO;
import Dtos.ProveedorDTO;
import Modelos.ModeloCliente;
import Modelos.ModeloProveedor;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jose rivera
 */
public class Registro extends javax.swing.JFrame {

    public static String tipoUsuarios;
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }
    
    public void iniciarComo(String tipoLogin) {
        tipoUsuarios = tipoLogin;
        
        this.setTitle(tipoLogin);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtPasswordV = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtTelfono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 207, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-fastore.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arroba-pink.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password-pink.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telefono-pink.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ubicacion-pink.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arroba-pink.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password-pink.png"))); // NOI18N

        btnRegistro.setBackground(new java.awt.Color(184, 164, 151));
        btnRegistro.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(252, 248, 232));
        btnRegistro.setText("Registrarse >");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(252, 248, 232));
        txtNombre.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(184, 164, 151));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("Nombre de la Empresa");

        txtCorreo.setBackground(new java.awt.Color(252, 248, 232));
        txtCorreo.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(184, 164, 151));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText("Correo");

        txtPassword.setBackground(new java.awt.Color(252, 248, 232));
        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(184, 164, 151));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("Contraseña");

        txtPasswordV.setBackground(new java.awt.Color(252, 248, 232));
        txtPasswordV.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtPasswordV.setForeground(new java.awt.Color(184, 164, 151));
        txtPasswordV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasswordV.setText("Confirmar Contraseña");

        txtUbicacion.setBackground(new java.awt.Color(252, 248, 232));
        txtUbicacion.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtUbicacion.setForeground(new java.awt.Color(184, 164, 151));
        txtUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUbicacion.setText("Ubicacion");

        txtTelfono.setBackground(new java.awt.Color(252, 248, 232));
        txtTelfono.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        txtTelfono.setForeground(new java.awt.Color(184, 164, 151));
        txtTelfono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelfono.setText("Telefono");
        txtTelfono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelfonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordV, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelfono, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtPasswordV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTelfono, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(52, 52, 52)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
   
       if("CLIENTE".equals(this.tipoUsuarios)) {
           registrarCliente();
        }
        
        if("PROVEEDOR".equals(this.tipoUsuarios)) {
            registrarProveedor();
        }
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    
    public boolean esEmail(String correo) {

        // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher mather = pattern.matcher(correo); //hara la validacion del string con el patron que se esta indicando

        return mather.find(); //indicara si lo encontro o no lo encontro

    } 
    
    private void registrarCliente(){
        
        //esto es la validacion de las contraseñas
        String Cont = new String(txtPassword.getText()); //es para que nos devuelva un char en arreglo, pero para que sea mas facil este proceso, yodo sera convertido en string
        String Vcont = new String(txtPasswordV.getText());
        
        ModeloCliente mCliente = new ModeloCliente();
        ClienteDTO cliente = new ClienteDTO();
        
          if (txtNombre.getText().equals("")
                || txtUbicacion.getText().equals("")
                || txtTelfono.getText().equals("")
                || txtCorreo.getText().equals("")
                || txtPassword.equals("")
                || txtPasswordV.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, por favor llene todos los campos");
        } else {

            if (Cont.equals(Vcont)) {
                //validacion de usuario, que no haya otro usuario igual registrado
                if (mCliente.existeCliente(txtNombre.getText()) == 0) {
                    if (esEmail(txtCorreo.getText())) {

                        String nuevoPass = hash.sha1(Cont);
                        cliente.setNombre(txtNombre.getText());
                        cliente.setUbicacion(txtUbicacion.getText());
                        cliente.setTelefono(txtTelfono.getText());
                        cliente.setCorreo(txtCorreo.getText());
                        cliente.setPassword(nuevoPass);

                        if (mCliente.registrar(cliente)) {
                            JOptionPane.showMessageDialog(null, "¡HAS SIDO REGISTRADO!");
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error de registro");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correo no es valido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las Contraseñas no Coinciden");
            }
        }

        
    }
    
    private void registrarProveedor(){
        //esto es la validacion de las contraseñas
        String Cont = new String(txtPassword.getText()); //es para que nos devuelva un char en arreglo, pero para que sea mas facil este proceso, yodo sera convertido en string
        String Vcont = new String(txtPasswordV.getText());
        
        ModeloProveedor mProveedor = new ModeloProveedor();
        ProveedorDTO proveedor = new ProveedorDTO();
        
          if (txtNombre.getText().equals("")
                || txtUbicacion.getText().equals("")
                || txtTelfono.getText().equals("")
                || txtCorreo.getText().equals("")
                || txtPassword.equals("")
                || txtPasswordV.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, por favor llene todos los campos");
        } else {

            if (Cont.equals(Vcont)) {
                //validacion de usuario, que no haya otro usuario igual registrado
                if (mProveedor.existeProveedor(txtNombre.getText()) == 0) {
                    if (esEmail(txtCorreo.getText())) {

                        String nuevoPass = hash.sha1(Cont);
                        proveedor.setNombre(txtNombre.getText());
                        proveedor.setUbicacion(txtUbicacion.getText());
                        proveedor.setTelefono(txtTelfono.getText());
                        proveedor.setCorreo(txtCorreo.getText());
                        proveedor.setPassword(nuevoPass);

                        if (mProveedor.registrar(proveedor)) {
                            JOptionPane.showMessageDialog(null, "¡HAS SIDO REGISTRADO!");
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error de registro");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correo no es valido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las Contraseñas no Coinciden");
            }
        }

    }
    
    private void validarContrasena(){
        
        if(txtPassword.getText() != txtPasswordV.getText()){
            JOptionPane.showMessageDialog(null, "Las constrasenas no coinciden");
        }
        
    }
    
    private void txtTelfonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelfonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelfonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordV;
    private javax.swing.JTextField txtTelfono;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
